// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rollmean_fc
NumericVector rollmean_fc(NumericVector x, NumericVector y, NumericVector xout, double width);
RcppExport SEXP wellz_rollmean_fc(SEXP xSEXP, SEXP ySEXP, SEXP xoutSEXP, SEXP widthSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP );
        Rcpp::traits::input_parameter< NumericVector >::type xout(xoutSEXP );
        Rcpp::traits::input_parameter< double >::type width(widthSEXP );
        NumericVector __result = rollmean_fc(x, y, xout, width);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
