# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' A very fast rolling mean with "INTERVAL"
#'
#' zoo::rollmean finds the "neighborhood" for the local mean by
#' finding the "k" closest points. This function finds all the
#' points that are distance "width" away from the point of interest
rollmean_fc <- function(x, y, xout, width) {
    .Call('wellz_rollmean_fc', PACKAGE = 'wellz', x, y, xout, width)
}

